Created Migration
Git-HQD/Hotel-Management-Online pull request #2
Opened 2022-07-20 01:26 UTC by KaiDioz

2022-07-20 03:21 UTC, duylinhng95 requested changes

2022-07-20 03:21 UTC, duylinhng95 commented on src/config/config.json
>      "dialect": "mysql"
push cả config lên chi vậy.

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125511-create_services_table.js
> +
xóa 2 line ni đi nghe. Cái ni do lib nó generate ra

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125511-create_services_table.js
> +      },
services có name_id làm gì nhỉ?

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125511-create_services_table.js
> +    }
cái dấu ngoặc đang sai vị trí. Thụt ra 1 chút

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125544-create_users_table.js
> +const { toDefaultValue } = require("sequelize/types/utils");
xóa import k xài

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125544-create_users_table.js
> +
xóa 2 line ni

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125544-create_users_table.js
> +
dư line.

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125544-create_users_table.js
> +      },
Mấy field này có cái nào allowNull k?

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719145000-create_room_type.js
> +'use strict';
xóa line này

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719145000-create_room_type.js
> +      await queryInterface.createTable('room_type',{
room_types. Tên table phải là số nhiều

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719145632-create_rooms.js
> +        room_type_Id:{
room_type_id.

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719145632-create_rooms.js
> +       })
thụt dòng bị sai

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719151536-create_bookings.js
> +
dư line

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719151536-create_bookings.js
> +    }
Mấy cái này không nullable à?

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719152349-create_booking_room.js
> +      rooms_id:{
room_id

2022-07-20 03:21 UTC, duylinhng95 commented on src/databases/migrations/20220719152349-create_booking_room.js
> +      bookings_id:{
booking_id

2022-07-20 03:54 UTC, KaiDioz commented on src/databases/migrations/20220719125511-create_services_table.js
> +    }
cái ngoặc nào mà sai vị trí vậy

2022-07-22 07:21 UTC, duylinhng95 commented on src/databases/migrations/20220719125511-create_services_table.js
> +    }
ngoặc dòng 25

2022-07-22 11:31 UTC, duylinhng95 requested changes

2022-07-22 11:31 UTC, duylinhng95 commented on src/databases/migrations/20220719125511-create_services_table.js
> +      name_service:{
name thôi. k cần phải name_service

2022-07-22 11:31 UTC, duylinhng95 commented on src/databases/migrations/20220719145000-create_room_type.js
> +        room_name:{
name thôi. Ko cần room_name

2022-07-22 11:31 UTC, duylinhng95 commented on src/databases/migrations/20220719145000-create_room_type.js
> +        service_id:{
1 loại phòng chỉ có 1 dịch vụ thôi à? Check lại logic chỗ này

2022-07-22 15:50 UTC, duylinhng95 approved these changes

2022-07-22 15:54 UTC, duylinhng95 commented on src/databases/migrations/20220719125511-create_services_table.js
> +      room_type_id:{
sửa lại quan hệ

2022-07-24 08:54 UTC, duylinhng95 commented on src/databases/migrations/20220719151536-create_bookings.js
> +        type: Sequelize.DataTypes.ENUM('comfirmed', 'cancelled', 'pendding', 'check_in', 'check_out')
`confirmed` và `pending`. Viết sai chính tả kìa

2022-07-24 08:55 UTC, duylinhng95 commented on src/databases/migrations/20220723045146-create_service_room.js
> +const { DataTypes } = require("sequelize/types");
Hình như không xài đúng k? K xài thì xóa nhé

2022-07-24 08:55 UTC, duylinhng95 commented on src/databases/migrations/20220719152349-create_booking_room.js
> +    await queryInterface.createTable('booking_room',{
`booking_rooms` hay `booking_room`?

2022-07-24 10:21 UTC, duylinhng95 approved these changes

2022-07-24 10:22 UTC, merged