finish-creating-user-api
Git-HQD/Hotel-Management-Online pull request #7
Opened 2022-07-21 02:32 UTC by Git-HQD

2022-07-21 09:28 UTC, duylinhng95 requested changes

2022-07-21 09:28 UTC, duylinhng95 commented on src/controllers/user.controller.js
> +const deLete = async(req, res) => {
delete. chữ L viết hoa rồi kìa

2022-07-21 09:28 UTC, duylinhng95 commented on src/controllers/user.controller.js
> +  const user = await userService.updateService(id, data);
trước câu lệnh gọi hàm thì enter xuống hàng nha

2022-07-21 09:28 UTC, duylinhng95 commented on src/controllers/user.controller.js
> +  res.status(200).json(user);
status 204 là được rồi k cần return user

2022-07-21 09:28 UTC, duylinhng95 commented on src/models/user.model.js
> +module.exports = (sequelize, DataTypes) => {
sửa lại model sử dụng cái sequelize.define cho nó rõ ràng chút.

2022-07-21 09:28 UTC, duylinhng95 commented on src/models/user.model.js
> +module.exports = (sequelize, DataTypes) => {
Trước `module.exports` thì cách hàng ra.

2022-07-21 09:28 UTC, duylinhng95 commented on src/models/user.model.js
> +"use strict";
xóa cái này

2022-07-21 09:28 UTC, duylinhng95 commented on src/server.js
> +
dư line

2022-07-22 01:01 UTC, Git-HQD commented on src/controllers/user.controller.js
> +const deLete = async(req, res) => {
đặt biến delete không nó báo lỗi syntax

2022-07-22 01:03 UTC, Git-HQD commented on src/controllers/user.controller.js
> +  const user = await userService.updateService(id, data);
xong

2022-07-22 01:05 UTC, Git-HQD commented on src/controllers/user.controller.js
> +  res.status(200).json(user);
xong

2022-07-22 02:43 UTC, Git-HQD commented on src/models/user.model.js
> +"use strict";
xong

2022-07-22 02:44 UTC, Git-HQD commented on src/server.js
> +
dư cái nào thế

2022-07-22 03:25 UTC, duylinhng95 commented on src/controllers/user.controller.js
> +const deLete = async(req, res) => {
đổi thành deleteUser

2022-07-22 03:27 UTC, Git-HQD commented on src/models/user.model.js
> +module.exports = (sequelize, DataTypes) => {
xong

2022-07-22 03:27 UTC, Git-HQD commented on src/controllers/user.controller.js
> +const deLete = async(req, res) => {
xong

2022-07-22 03:42 UTC, duylinhng95 commented on src/server.js
> +
dư line 6 7 kìa xóa 1 line đi

2022-07-22 03:55 UTC, duylinhng95 commented on src/models/user.model.js
> +    "users",
tên model số ít viết hoa chữ cái đầu (Capitalize). User

2022-07-22 03:57 UTC, duylinhng95 commented on src/services/users.service.js
> +const deLete = async (userId, data) => {
`deleteUser`

2022-07-22 03:57 UTC, duylinhng95 commented on src/services/users.service.js
> +  return;
function void k cần return

2022-07-22 04:03 UTC, Git-HQD commented on src/models/user.model.js
> +    "users",
xong

2022-07-22 04:03 UTC, Git-HQD commented on src/services/users.service.js
> +const deLete = async (userId, data) => {
xong

2022-07-22 04:04 UTC, Git-HQD commented on src/services/users.service.js
> +  return;
xong

2022-07-22 07:20 UTC, duylinhng95 commented on package.json
> +    "sqlite3": "^5.0.9"
xóa package ni đi nghe. Mình k xài sqlite3

2022-07-23 06:46 UTC, Git-HQD commented on package.json
> +    "sqlite3": "^5.0.9"
xong r

2022-07-23 07:00 UTC, duylinhng95 approved these changes

2022-07-23 07:01 UTC, merged